### ISSUE TITLE
Use a dictionary for storing style properties to reduce memory usage

### ISSUE THREAD

**Issue by sdevos** [Q42/StyledString#10]

**Comment by tomlokhorst** [comment]
Maybe this can also help with setting multiple style properties at once?

For example; In my current NSAttributedString code I have a NSMutableParagraphStyle, whose style I can set all at once:

``` swift
    let listParagraphStyle = NSMutableParagraphStyle()
    listParagraphStyle.headIndent = 9
    listParagraphStyle.lineSpacing = 4
    listParagraphStyle.firstLineHeadIndent = 0
```

With Styled string, I have to set these values separately:

``` swift
    let new = original
      .withHeadIndent(9)
      .withLineSpacing(4)
      .withFirstLineHeadIndent(0)
```

It would be nice to have something that is the equivalent of NSParagraphStyle.

**Comment by tomlokhorst** [comment]
Implemented in https://github.com/Q42/StyledString/pull/24
